//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.MailService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://tempuri.org/")]
    public partial class Attachment : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailResult", Namespace="http://tempuri.org/")]
    public partial class EmailResult : object
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOS.MailService.SendEmailV2Soap")]
    public interface SendEmailV2Soap
    {
        
        // CODEGEN: Generating message contract since element name senderEmailAddress from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueueEmailMessage", ReplyAction="*")]
        BOS.MailService.QueueEmailMessageResponse QueueEmailMessage(BOS.MailService.QueueEmailMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueueEmailMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<BOS.MailService.QueueEmailMessageResponse> QueueEmailMessageAsync(BOS.MailService.QueueEmailMessageRequest request);
        
        // CODEGEN: Generating message contract since element name senderEmailAddress from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailTo", ReplyAction="*")]
        BOS.MailService.SendEmailToResponse SendEmailTo(BOS.MailService.SendEmailToRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailTo", ReplyAction="*")]
        System.Threading.Tasks.Task<BOS.MailService.SendEmailToResponse> SendEmailToAsync(BOS.MailService.SendEmailToRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueueEmailMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueueEmailMessage", Namespace="http://tempuri.org/", Order=0)]
        public BOS.MailService.QueueEmailMessageRequestBody Body;
        
        public QueueEmailMessageRequest()
        {
        }
        
        public QueueEmailMessageRequest(BOS.MailService.QueueEmailMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueueEmailMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderEmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BOS.MailService.ArrayOfString emailAddresses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int priority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BOS.MailService.Attachment[] attachmentFiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string encoding;
        
        public QueueEmailMessageRequestBody()
        {
        }
        
        public QueueEmailMessageRequestBody(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string messageBody, int priority, BOS.MailService.Attachment[] attachmentFiles, string encoding)
        {
            this.senderEmailAddress = senderEmailAddress;
            this.senderName = senderName;
            this.emailAddresses = emailAddresses;
            this.subject = subject;
            this.messageBody = messageBody;
            this.priority = priority;
            this.attachmentFiles = attachmentFiles;
            this.encoding = encoding;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueueEmailMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueueEmailMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public BOS.MailService.QueueEmailMessageResponseBody Body;
        
        public QueueEmailMessageResponse()
        {
        }
        
        public QueueEmailMessageResponse(BOS.MailService.QueueEmailMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QueueEmailMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BOS.MailService.EmailResult QueueEmailMessageResult;
        
        public QueueEmailMessageResponseBody()
        {
        }
        
        public QueueEmailMessageResponseBody(BOS.MailService.EmailResult QueueEmailMessageResult)
        {
            this.QueueEmailMessageResult = QueueEmailMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailToRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailTo", Namespace="http://tempuri.org/", Order=0)]
        public BOS.MailService.SendEmailToRequestBody Body;
        
        public SendEmailToRequest()
        {
        }
        
        public SendEmailToRequest(BOS.MailService.SendEmailToRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailToRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderEmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BOS.MailService.ArrayOfString emailAddresses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BOS.MailService.ArrayOfString attachmentFiles;
        
        public SendEmailToRequestBody()
        {
        }
        
        public SendEmailToRequestBody(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string message, BOS.MailService.ArrayOfString attachmentFiles)
        {
            this.senderEmailAddress = senderEmailAddress;
            this.senderName = senderName;
            this.emailAddresses = emailAddresses;
            this.subject = subject;
            this.message = message;
            this.attachmentFiles = attachmentFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailToResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailToResponse", Namespace="http://tempuri.org/", Order=0)]
        public BOS.MailService.SendEmailToResponseBody Body;
        
        public SendEmailToResponse()
        {
        }
        
        public SendEmailToResponse(BOS.MailService.SendEmailToResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailToResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BOS.MailService.EmailResult SendEmailToResult;
        
        public SendEmailToResponseBody()
        {
        }
        
        public SendEmailToResponseBody(BOS.MailService.EmailResult SendEmailToResult)
        {
            this.SendEmailToResult = SendEmailToResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SendEmailV2SoapChannel : BOS.MailService.SendEmailV2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SendEmailV2SoapClient : System.ServiceModel.ClientBase<BOS.MailService.SendEmailV2Soap>, BOS.MailService.SendEmailV2Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendEmailV2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendEmailV2SoapClient.GetBindingForEndpoint(endpointConfiguration), SendEmailV2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendEmailV2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendEmailV2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendEmailV2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendEmailV2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendEmailV2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOS.MailService.QueueEmailMessageResponse BOS.MailService.SendEmailV2Soap.QueueEmailMessage(BOS.MailService.QueueEmailMessageRequest request)
        {
            return base.Channel.QueueEmailMessage(request);
        }
        
        public BOS.MailService.EmailResult QueueEmailMessage(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string messageBody, int priority, BOS.MailService.Attachment[] attachmentFiles, string encoding)
        {
            BOS.MailService.QueueEmailMessageRequest inValue = new BOS.MailService.QueueEmailMessageRequest();
            inValue.Body = new BOS.MailService.QueueEmailMessageRequestBody();
            inValue.Body.senderEmailAddress = senderEmailAddress;
            inValue.Body.senderName = senderName;
            inValue.Body.emailAddresses = emailAddresses;
            inValue.Body.subject = subject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.priority = priority;
            inValue.Body.attachmentFiles = attachmentFiles;
            inValue.Body.encoding = encoding;
            BOS.MailService.QueueEmailMessageResponse retVal = ((BOS.MailService.SendEmailV2Soap)(this)).QueueEmailMessage(inValue);
            return retVal.Body.QueueEmailMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOS.MailService.QueueEmailMessageResponse> BOS.MailService.SendEmailV2Soap.QueueEmailMessageAsync(BOS.MailService.QueueEmailMessageRequest request)
        {
            return base.Channel.QueueEmailMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOS.MailService.QueueEmailMessageResponse> QueueEmailMessageAsync(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string messageBody, int priority, BOS.MailService.Attachment[] attachmentFiles, string encoding)
        {
            BOS.MailService.QueueEmailMessageRequest inValue = new BOS.MailService.QueueEmailMessageRequest();
            inValue.Body = new BOS.MailService.QueueEmailMessageRequestBody();
            inValue.Body.senderEmailAddress = senderEmailAddress;
            inValue.Body.senderName = senderName;
            inValue.Body.emailAddresses = emailAddresses;
            inValue.Body.subject = subject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.priority = priority;
            inValue.Body.attachmentFiles = attachmentFiles;
            inValue.Body.encoding = encoding;
            return ((BOS.MailService.SendEmailV2Soap)(this)).QueueEmailMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BOS.MailService.SendEmailToResponse BOS.MailService.SendEmailV2Soap.SendEmailTo(BOS.MailService.SendEmailToRequest request)
        {
            return base.Channel.SendEmailTo(request);
        }
        
        public BOS.MailService.EmailResult SendEmailTo(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string message, BOS.MailService.ArrayOfString attachmentFiles)
        {
            BOS.MailService.SendEmailToRequest inValue = new BOS.MailService.SendEmailToRequest();
            inValue.Body = new BOS.MailService.SendEmailToRequestBody();
            inValue.Body.senderEmailAddress = senderEmailAddress;
            inValue.Body.senderName = senderName;
            inValue.Body.emailAddresses = emailAddresses;
            inValue.Body.subject = subject;
            inValue.Body.message = message;
            inValue.Body.attachmentFiles = attachmentFiles;
            BOS.MailService.SendEmailToResponse retVal = ((BOS.MailService.SendEmailV2Soap)(this)).SendEmailTo(inValue);
            return retVal.Body.SendEmailToResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BOS.MailService.SendEmailToResponse> BOS.MailService.SendEmailV2Soap.SendEmailToAsync(BOS.MailService.SendEmailToRequest request)
        {
            return base.Channel.SendEmailToAsync(request);
        }
        
        public System.Threading.Tasks.Task<BOS.MailService.SendEmailToResponse> SendEmailToAsync(string senderEmailAddress, string senderName, BOS.MailService.ArrayOfString emailAddresses, string subject, string message, BOS.MailService.ArrayOfString attachmentFiles)
        {
            BOS.MailService.SendEmailToRequest inValue = new BOS.MailService.SendEmailToRequest();
            inValue.Body = new BOS.MailService.SendEmailToRequestBody();
            inValue.Body.senderEmailAddress = senderEmailAddress;
            inValue.Body.senderName = senderName;
            inValue.Body.emailAddresses = emailAddresses;
            inValue.Body.subject = subject;
            inValue.Body.message = message;
            inValue.Body.attachmentFiles = attachmentFiles;
            return ((BOS.MailService.SendEmailV2Soap)(this)).SendEmailToAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendEmailV2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendEmailV2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendEmailV2Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://test-notification-v2.birlesikodeme.com:58245/SendEmailV2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendEmailV2Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://test-notification-v2.birlesikodeme.com:58245/SendEmailV2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendEmailV2Soap,
            
            SendEmailV2Soap12,
        }
    }
}
