//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simant.TransportationService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityCredentials", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Business")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.RegisterCardParam))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.GetCardsByIntegrationMatchingDataRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.UpdateCustomerCardholderInformationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.CreateCardsIndividuallyParam))]
    public partial class SecurityCredentials : object
    {
        
        private string PasswordField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterCardParam", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Business")]
    public partial class RegisterCardParam : Simant.TransportationService.SecurityCredentials
    {
        
        private System.Nullable<int> CardidField;
        
        private string ChannelidField;
        
        private string CitizennumberField;
        
        private System.Nullable<System.DateTime> DatebirthField;
        
        private string EmailField;
        
        private string IntegrationMatchingDataField;
        
        private string Last4digitField;
        
        private string MobilephonenumberField;
        
        private string NameField;
        
        private string PlacebirthField;
        
        private string SecondnameField;
        
        private string SurnameField;
        
        private string TaxidField;
        
        private string UseridField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cardid
        {
            get
            {
                return this.CardidField;
            }
            set
            {
                this.CardidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channelid
        {
            get
            {
                return this.ChannelidField;
            }
            set
            {
                this.ChannelidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizennumber
        {
            get
            {
                return this.CitizennumberField;
            }
            set
            {
                this.CitizennumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datebirth
        {
            get
            {
                return this.DatebirthField;
            }
            set
            {
                this.DatebirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegrationMatchingData
        {
            get
            {
                return this.IntegrationMatchingDataField;
            }
            set
            {
                this.IntegrationMatchingDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last4digit
        {
            get
            {
                return this.Last4digitField;
            }
            set
            {
                this.Last4digitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobilephonenumber
        {
            get
            {
                return this.MobilephonenumberField;
            }
            set
            {
                this.MobilephonenumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placebirth
        {
            get
            {
                return this.PlacebirthField;
            }
            set
            {
                this.PlacebirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secondname
        {
            get
            {
                return this.SecondnameField;
            }
            set
            {
                this.SecondnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Taxid
        {
            get
            {
                return this.TaxidField;
            }
            set
            {
                this.TaxidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userid
        {
            get
            {
                return this.UseridField;
            }
            set
            {
                this.UseridField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCardsByIntegrationMatchingDataRequest", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class GetCardsByIntegrationMatchingDataRequest : Simant.TransportationService.SecurityCredentials
    {
        
        private string IntegrationMatchingDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegrationMatchingData
        {
            get
            {
                return this.IntegrationMatchingDataField;
            }
            set
            {
                this.IntegrationMatchingDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmCardTransactionsByIntegrationMatchingDataRequest", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CrmCardTransactionsByIntegrationMatchingDataRequest : Simant.TransportationService.SecurityCredentials
    {
        
        private System.Nullable<System.DateTime> DateendField;
        
        private System.Nullable<System.DateTime> DatestartField;
        
        private string IntegrationMatchingDataField;
        
        private string OrderByField;
        
        private int PagenumberField;
        
        private int PagesizeField;
        
        private string StatusCodeField;
        
        private string TransactionCodeField;
        
        private string TransactionModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dateend
        {
            get
            {
                return this.DateendField;
            }
            set
            {
                this.DateendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datestart
        {
            get
            {
                return this.DatestartField;
            }
            set
            {
                this.DatestartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegrationMatchingData
        {
            get
            {
                return this.IntegrationMatchingDataField;
            }
            set
            {
                this.IntegrationMatchingDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagenumber
        {
            get
            {
                return this.PagenumberField;
            }
            set
            {
                this.PagenumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagesize
        {
            get
            {
                return this.PagesizeField;
            }
            set
            {
                this.PagesizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionMode
        {
            get
            {
                return this.TransactionModeField;
            }
            set
            {
                this.TransactionModeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmCardTransactionsByCardIdsRequest", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CrmCardTransactionsByCardIdsRequest : Simant.TransportationService.SecurityCredentials
    {
        
        private string CardAcceptorIdField;
        
        private string CardAcceptorTerminalIdField;
        
        private int[] CardIDsField;
        
        private string ChannelIdField;
        
        private System.Nullable<System.DateTime> DateendField;
        
        private System.Nullable<System.DateTime> DatestartField;
        
        private string[] IgnoreTransactionCodeListField;
        
        private string[] IgnoreTransactionModeListField;
        
        private string OrderByField;
        
        private int PagenumberField;
        
        private int PagesizeField;
        
        private System.Nullable<bool> RefundflagField;
        
        private System.Nullable<bool> ReverseflagField;
        
        private string StatusCodeField;
        
        private string[] TransactionCodeListField;
        
        private string TransactionModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorId
        {
            get
            {
                return this.CardAcceptorIdField;
            }
            set
            {
                this.CardAcceptorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorTerminalId
        {
            get
            {
                return this.CardAcceptorTerminalIdField;
            }
            set
            {
                this.CardAcceptorTerminalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] CardIDs
        {
            get
            {
                return this.CardIDsField;
            }
            set
            {
                this.CardIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dateend
        {
            get
            {
                return this.DateendField;
            }
            set
            {
                this.DateendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datestart
        {
            get
            {
                return this.DatestartField;
            }
            set
            {
                this.DatestartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] IgnoreTransactionCodeList
        {
            get
            {
                return this.IgnoreTransactionCodeListField;
            }
            set
            {
                this.IgnoreTransactionCodeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] IgnoreTransactionModeList
        {
            get
            {
                return this.IgnoreTransactionModeListField;
            }
            set
            {
                this.IgnoreTransactionModeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagenumber
        {
            get
            {
                return this.PagenumberField;
            }
            set
            {
                this.PagenumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagesize
        {
            get
            {
                return this.PagesizeField;
            }
            set
            {
                this.PagesizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Refundflag
        {
            get
            {
                return this.RefundflagField;
            }
            set
            {
                this.RefundflagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Reverseflag
        {
            get
            {
                return this.ReverseflagField;
            }
            set
            {
                this.ReverseflagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TransactionCodeList
        {
            get
            {
                return this.TransactionCodeListField;
            }
            set
            {
                this.TransactionCodeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionMode
        {
            get
            {
                return this.TransactionModeField;
            }
            set
            {
                this.TransactionModeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerCardholderInformationRequest", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class UpdateCustomerCardholderInformationRequest : Simant.TransportationService.SecurityCredentials
    {
        
        private System.Nullable<int> CardIdField;
        
        private System.Nullable<int> CardholderIdField;
        
        private string ChannelIdField;
        
        private string CitizenNumberField;
        
        private System.Nullable<int> CustomerIdField;
        
        private string NewEmailField;
        
        private string NewNameField;
        
        private string NewPhoneNumberField;
        
        private string NewSecondNameField;
        
        private string NewSurnameField;
        
        private string OldEmailField;
        
        private string OldPhoneNumberField;
        
        private bool UpdateEmailFlagField;
        
        private bool UpdateNameFlagField;
        
        private bool UpdatePhoneNumberFlagField;
        
        private bool UpdateSecondNameFlagField;
        
        private bool UpdateSurnameFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CardId
        {
            get
            {
                return this.CardIdField;
            }
            set
            {
                this.CardIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CardholderId
        {
            get
            {
                return this.CardholderIdField;
            }
            set
            {
                this.CardholderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenNumber
        {
            get
            {
                return this.CitizenNumberField;
            }
            set
            {
                this.CitizenNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewEmail
        {
            get
            {
                return this.NewEmailField;
            }
            set
            {
                this.NewEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewName
        {
            get
            {
                return this.NewNameField;
            }
            set
            {
                this.NewNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPhoneNumber
        {
            get
            {
                return this.NewPhoneNumberField;
            }
            set
            {
                this.NewPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewSecondName
        {
            get
            {
                return this.NewSecondNameField;
            }
            set
            {
                this.NewSecondNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewSurname
        {
            get
            {
                return this.NewSurnameField;
            }
            set
            {
                this.NewSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldEmail
        {
            get
            {
                return this.OldEmailField;
            }
            set
            {
                this.OldEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldPhoneNumber
        {
            get
            {
                return this.OldPhoneNumberField;
            }
            set
            {
                this.OldPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdateEmailFlag
        {
            get
            {
                return this.UpdateEmailFlagField;
            }
            set
            {
                this.UpdateEmailFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdateNameFlag
        {
            get
            {
                return this.UpdateNameFlagField;
            }
            set
            {
                this.UpdateNameFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdatePhoneNumberFlag
        {
            get
            {
                return this.UpdatePhoneNumberFlagField;
            }
            set
            {
                this.UpdatePhoneNumberFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdateSecondNameFlag
        {
            get
            {
                return this.UpdateSecondNameFlagField;
            }
            set
            {
                this.UpdateSecondNameFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UpdateSurnameFlag
        {
            get
            {
                return this.UpdateSurnameFlagField;
            }
            set
            {
                this.UpdateSurnameFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateCardsIndividuallyParam", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CreateCardsIndividuallyParam : Simant.TransportationService.SecurityCredentials
    {
        
        private int BankCustomeridField;
        
        private string ChannelIdField;
        
        private string CitizenNumberField;
        
        private System.DateTime DateBirthField;
        
        private string FatherNameField;
        
        private int GroupIdField;
        
        private string IntegrationMatchingDataField;
        
        private string MobilePhoneNumberField;
        
        private string NameField;
        
        private string PlaceBirthField;
        
        private string ProductIdField;
        
        private string SecondNameField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankCustomerid
        {
            get
            {
                return this.BankCustomeridField;
            }
            set
            {
                this.BankCustomeridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenNumber
        {
            get
            {
                return this.CitizenNumberField;
            }
            set
            {
                this.CitizenNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBirth
        {
            get
            {
                return this.DateBirthField;
            }
            set
            {
                this.DateBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName
        {
            get
            {
                return this.FatherNameField;
            }
            set
            {
                this.FatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegrationMatchingData
        {
            get
            {
                return this.IntegrationMatchingDataField;
            }
            set
            {
                this.IntegrationMatchingDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNumber
        {
            get
            {
                return this.MobilePhoneNumberField;
            }
            set
            {
                this.MobilePhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceBirth
        {
            get
            {
                return this.PlaceBirthField;
            }
            set
            {
                this.PlaceBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName
        {
            get
            {
                return this.SecondNameField;
            }
            set
            {
                this.SecondNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateCardsIndividually", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CreateCardsIndividually : object
    {
        
        private decimal AvailableBalanceField;
        
        private decimal AvailableLoadLimitField;
        
        private decimal AvailableLoyaltyBalanceField;
        
        private decimal AvailableWithdrawalLimitField;
        
        private string CVV2Field;
        
        private int CardIdField;
        
        private int CardholderIdField;
        
        private string ExpiryDateField;
        
        private string PANField;
        
        private int ResultField;
        
        private string ResultDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableBalance
        {
            get
            {
                return this.AvailableBalanceField;
            }
            set
            {
                this.AvailableBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableLoadLimit
        {
            get
            {
                return this.AvailableLoadLimitField;
            }
            set
            {
                this.AvailableLoadLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableLoyaltyBalance
        {
            get
            {
                return this.AvailableLoyaltyBalanceField;
            }
            set
            {
                this.AvailableLoyaltyBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableWithdrawalLimit
        {
            get
            {
                return this.AvailableWithdrawalLimitField;
            }
            set
            {
                this.AvailableWithdrawalLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV2
        {
            get
            {
                return this.CVV2Field;
            }
            set
            {
                this.CVV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId
        {
            get
            {
                return this.CardIdField;
            }
            set
            {
                this.CardIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardholderId
        {
            get
            {
                return this.CardholderIdField;
            }
            set
            {
                this.CardholderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAN
        {
            get
            {
                return this.PANField;
            }
            set
            {
                this.PANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendResultClass", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Business")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.RegisterCardResult))]
    public partial class ExtendResultClass : object
    {
        
        private System.Nullable<int> ResultField;
        
        private string ResultDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterCardResult", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Business")]
    public partial class RegisterCardResult : Simant.TransportationService.ExtendResultClass
    {
        
        private System.Nullable<decimal> AvailablecardbalanceField;
        
        private System.Nullable<decimal> AvailablecashlimitField;
        
        private System.Nullable<decimal> AvailableloadlimitField;
        
        private string CardnoField;
        
        private string CvvField;
        
        private System.Nullable<System.DateTime> ExpirydateField;
        
        private System.Nullable<decimal> LoyaltybalanceField;
        
        private string StatusField;
        
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Availablecardbalance
        {
            get
            {
                return this.AvailablecardbalanceField;
            }
            set
            {
                this.AvailablecardbalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Availablecashlimit
        {
            get
            {
                return this.AvailablecashlimitField;
            }
            set
            {
                this.AvailablecashlimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Availableloadlimit
        {
            get
            {
                return this.AvailableloadlimitField;
            }
            set
            {
                this.AvailableloadlimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cardno
        {
            get
            {
                return this.CardnoField;
            }
            set
            {
                this.CardnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Expirydate
        {
            get
            {
                return this.ExpirydateField;
            }
            set
            {
                this.ExpirydateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Loyaltybalance
        {
            get
            {
                return this.LoyaltybalanceField;
            }
            set
            {
                this.LoyaltybalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCardsByIntegrationMatchingDataResponse", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class GetCardsByIntegrationMatchingDataResponse : object
    {
        
        private Simant.TransportationService.CardData[] CardsField;
        
        private int ResultField;
        
        private string ResultDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Simant.TransportationService.CardData[] Cards
        {
            get
            {
                return this.CardsField;
            }
            set
            {
                this.CardsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardData", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CardData : object
    {
        
        private int CardidField;
        
        private string NameField;
        
        private System.DateTime RegistereddateField;
        
        private string SecondnameField;
        
        private string StatusField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cardid
        {
            get
            {
                return this.CardidField;
            }
            set
            {
                this.CardidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registereddate
        {
            get
            {
                return this.RegistereddateField;
            }
            set
            {
                this.RegistereddateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secondname
        {
            get
            {
                return this.SecondnameField;
            }
            set
            {
                this.SecondnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmCardTransactionsByIntegrationMatchingDataResponse", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CrmCardTransactionsByIntegrationMatchingDataResponse : object
    {
        
        private System.Nullable<int> CountField;
        
        private Simant.TransportationService.CrmCardTransactionData[] ListOfCrmCardTransactionDataField;
        
        private int ResultField;
        
        private string ResultDescField;
        
        private System.Nullable<int> ReturnCodeField;
        
        private string ReturnValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Simant.TransportationService.CrmCardTransactionData[] ListOfCrmCardTransactionData
        {
            get
            {
                return this.ListOfCrmCardTransactionDataField;
            }
            set
            {
                this.ListOfCrmCardTransactionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnValue
        {
            get
            {
                return this.ReturnValueField;
            }
            set
            {
                this.ReturnValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmCardTransactionData", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CrmCardTransactionData : object
    {
        
        private string AtmCityField;
        
        private string AtmCodeField;
        
        private string AtmCountryField;
        
        private string AtmNameField;
        
        private string AuthorizationCodeField;
        
        private string BankCodeField;
        
        private string BankDescriptionField;
        
        private string CardAcceptorCityNameField;
        
        private string CardAcceptorIdField;
        
        private string CardAcceptorNameField;
        
        private string CardAcceptorTerminalIdField;
        
        private int CardIdField;
        
        private string ChannelIdField;
        
        private string ContentField;
        
        private System.DateTime InsertDateField;
        
        private string IntegrationMatchingDataField;
        
        private string MaskedPanField;
        
        private string MerchantCategoryCodeField;
        
        private string MerchantDescriptionField;
        
        private string ProductCodeField;
        
        private string RRNField;
        
        private bool RefundFlagField;
        
        private string ResponseCodeField;
        
        private string ResponseReasonCodeField;
        
        private string ResponseReasonCodeDescriptionField;
        
        private bool ReverseFlagField;
        
        private int RowidField;
        
        private decimal SourceAmountField;
        
        private string SourceCurrencyCodeField;
        
        private string TransactionCodeField;
        
        private System.DateTime TransactionDateField;
        
        private int TransactionIdField;
        
        private string TransactionModeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtmCity
        {
            get
            {
                return this.AtmCityField;
            }
            set
            {
                this.AtmCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtmCode
        {
            get
            {
                return this.AtmCodeField;
            }
            set
            {
                this.AtmCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtmCountry
        {
            get
            {
                return this.AtmCountryField;
            }
            set
            {
                this.AtmCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtmName
        {
            get
            {
                return this.AtmNameField;
            }
            set
            {
                this.AtmNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorizationCode
        {
            get
            {
                return this.AuthorizationCodeField;
            }
            set
            {
                this.AuthorizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode
        {
            get
            {
                return this.BankCodeField;
            }
            set
            {
                this.BankCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankDescription
        {
            get
            {
                return this.BankDescriptionField;
            }
            set
            {
                this.BankDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorCityName
        {
            get
            {
                return this.CardAcceptorCityNameField;
            }
            set
            {
                this.CardAcceptorCityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorId
        {
            get
            {
                return this.CardAcceptorIdField;
            }
            set
            {
                this.CardAcceptorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorName
        {
            get
            {
                return this.CardAcceptorNameField;
            }
            set
            {
                this.CardAcceptorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAcceptorTerminalId
        {
            get
            {
                return this.CardAcceptorTerminalIdField;
            }
            set
            {
                this.CardAcceptorTerminalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId
        {
            get
            {
                return this.CardIdField;
            }
            set
            {
                this.CardIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegrationMatchingData
        {
            get
            {
                return this.IntegrationMatchingDataField;
            }
            set
            {
                this.IntegrationMatchingDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedPan
        {
            get
            {
                return this.MaskedPanField;
            }
            set
            {
                this.MaskedPanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCategoryCode
        {
            get
            {
                return this.MerchantCategoryCodeField;
            }
            set
            {
                this.MerchantCategoryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantDescription
        {
            get
            {
                return this.MerchantDescriptionField;
            }
            set
            {
                this.MerchantDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RRN
        {
            get
            {
                return this.RRNField;
            }
            set
            {
                this.RRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RefundFlag
        {
            get
            {
                return this.RefundFlagField;
            }
            set
            {
                this.RefundFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseReasonCode
        {
            get
            {
                return this.ResponseReasonCodeField;
            }
            set
            {
                this.ResponseReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseReasonCodeDescription
        {
            get
            {
                return this.ResponseReasonCodeDescriptionField;
            }
            set
            {
                this.ResponseReasonCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReverseFlag
        {
            get
            {
                return this.ReverseFlagField;
            }
            set
            {
                this.ReverseFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rowid
        {
            get
            {
                return this.RowidField;
            }
            set
            {
                this.RowidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SourceAmount
        {
            get
            {
                return this.SourceAmountField;
            }
            set
            {
                this.SourceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceCurrencyCode
        {
            get
            {
                return this.SourceCurrencyCodeField;
            }
            set
            {
                this.SourceCurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionMode
        {
            get
            {
                return this.TransactionModeField;
            }
            set
            {
                this.TransactionModeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmCardTransactionsByCardIdsResponse", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class CrmCardTransactionsByCardIdsResponse : object
    {
        
        private int CountField;
        
        private Simant.TransportationService.CrmCardTransactionData[] ListOfCrmCardTransactionDataField;
        
        private int ResultField;
        
        private string ResultDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Simant.TransportationService.CrmCardTransactionData[] ListOfCrmCardTransactionData
        {
            get
            {
                return this.ListOfCrmCardTransactionDataField;
            }
            set
            {
                this.ListOfCrmCardTransactionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportationResponseBase", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Simant.TransportationService.UpdateCustomerCardholderInformationResponse))]
    public partial class TransportationResponseBase : object
    {
        
        private int ResultField;
        
        private string ResultDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDesc
        {
            get
            {
                return this.ResultDescField;
            }
            set
            {
                this.ResultDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerCardholderInformationResponse", Namespace="http://schemas.datacontract.org/2004/07/SimAnt.Everest.BOS.Services.Integration")]
    public partial class UpdateCustomerCardholderInformationResponse : Simant.TransportationService.TransportationResponseBase
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Simant.TransportationService.ITransportationService")]
    public interface ITransportationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CreateCard", ReplyAction="http://tempuri.org/ITransportationService/CreateCardResponse")]
        Simant.TransportationService.CreateCardsIndividually CreateCard(Simant.TransportationService.CreateCardsIndividuallyParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CreateCard", ReplyAction="http://tempuri.org/ITransportationService/CreateCardResponse")]
        System.Threading.Tasks.Task<Simant.TransportationService.CreateCardsIndividually> CreateCardAsync(Simant.TransportationService.CreateCardsIndividuallyParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/RegisterCard", ReplyAction="http://tempuri.org/ITransportationService/RegisterCardResponse")]
        Simant.TransportationService.RegisterCardResult RegisterCard(Simant.TransportationService.RegisterCardParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/RegisterCard", ReplyAction="http://tempuri.org/ITransportationService/RegisterCardResponse")]
        System.Threading.Tasks.Task<Simant.TransportationService.RegisterCardResult> RegisterCardAsync(Simant.TransportationService.RegisterCardParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/GetCardsByIntegrationMatchingData", ReplyAction="http://tempuri.org/ITransportationService/GetCardsByIntegrationMatchingDataRespon" +
            "se")]
        Simant.TransportationService.GetCardsByIntegrationMatchingDataResponse GetCardsByIntegrationMatchingData(Simant.TransportationService.GetCardsByIntegrationMatchingDataRequest getCardsByIntegrationMatchingDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/GetCardsByIntegrationMatchingData", ReplyAction="http://tempuri.org/ITransportationService/GetCardsByIntegrationMatchingDataRespon" +
            "se")]
        System.Threading.Tasks.Task<Simant.TransportationService.GetCardsByIntegrationMatchingDataResponse> GetCardsByIntegrationMatchingDataAsync(Simant.TransportationService.GetCardsByIntegrationMatchingDataRequest getCardsByIntegrationMatchingDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByIntegrationMatchin" +
            "gData", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByIntegrationMatchin" +
            "gDataResponse")]
        Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataResponse CrmCardTransactionsByIntegrationMatchingData(Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataRequest param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByIntegrationMatchin" +
            "gData", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByIntegrationMatchin" +
            "gDataResponse")]
        System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataResponse> CrmCardTransactionsByIntegrationMatchingDataAsync(Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataRequest param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIds", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsResponse")]
        Simant.TransportationService.CrmCardTransactionsByCardIdsResponse CrmCardTransactionsByCardIds(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIds", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsResponse")]
        System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByCardIdsResponse> CrmCardTransactionsByCardIdsAsync(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsARS", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsARSResponse" +
            "")]
        Simant.TransportationService.CrmCardTransactionsByCardIdsResponse CrmCardTransactionsByCardIdsARS(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsARS", ReplyAction="http://tempuri.org/ITransportationService/CrmCardTransactionsByCardIdsARSResponse" +
            "")]
        System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByCardIdsResponse> CrmCardTransactionsByCardIdsARSAsync(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/UpdateCustomerCardholderInformation", ReplyAction="http://tempuri.org/ITransportationService/UpdateCustomerCardholderInformationResp" +
            "onse")]
        Simant.TransportationService.UpdateCustomerCardholderInformationResponse UpdateCustomerCardholderInformation(Simant.TransportationService.UpdateCustomerCardholderInformationRequest updateCustomerCardholderInformationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportationService/UpdateCustomerCardholderInformation", ReplyAction="http://tempuri.org/ITransportationService/UpdateCustomerCardholderInformationResp" +
            "onse")]
        System.Threading.Tasks.Task<Simant.TransportationService.UpdateCustomerCardholderInformationResponse> UpdateCustomerCardholderInformationAsync(Simant.TransportationService.UpdateCustomerCardholderInformationRequest updateCustomerCardholderInformationRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ITransportationServiceChannel : Simant.TransportationService.ITransportationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class TransportationServiceClient : System.ServiceModel.ClientBase<Simant.TransportationService.ITransportationService>, Simant.TransportationService.ITransportationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransportationServiceClient() : 
                base(TransportationServiceClient.GetDefaultBinding(), TransportationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITransportationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransportationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TransportationServiceClient.GetBindingForEndpoint(endpointConfiguration), TransportationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransportationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransportationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransportationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransportationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransportationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Simant.TransportationService.CreateCardsIndividually CreateCard(Simant.TransportationService.CreateCardsIndividuallyParam param)
        {
            return base.Channel.CreateCard(param);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.CreateCardsIndividually> CreateCardAsync(Simant.TransportationService.CreateCardsIndividuallyParam param)
        {
            return base.Channel.CreateCardAsync(param);
        }
        
        public Simant.TransportationService.RegisterCardResult RegisterCard(Simant.TransportationService.RegisterCardParam param)
        {
            return base.Channel.RegisterCard(param);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.RegisterCardResult> RegisterCardAsync(Simant.TransportationService.RegisterCardParam param)
        {
            return base.Channel.RegisterCardAsync(param);
        }
        
        public Simant.TransportationService.GetCardsByIntegrationMatchingDataResponse GetCardsByIntegrationMatchingData(Simant.TransportationService.GetCardsByIntegrationMatchingDataRequest getCardsByIntegrationMatchingDataRequest)
        {
            return base.Channel.GetCardsByIntegrationMatchingData(getCardsByIntegrationMatchingDataRequest);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.GetCardsByIntegrationMatchingDataResponse> GetCardsByIntegrationMatchingDataAsync(Simant.TransportationService.GetCardsByIntegrationMatchingDataRequest getCardsByIntegrationMatchingDataRequest)
        {
            return base.Channel.GetCardsByIntegrationMatchingDataAsync(getCardsByIntegrationMatchingDataRequest);
        }
        
        public Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataResponse CrmCardTransactionsByIntegrationMatchingData(Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataRequest param)
        {
            return base.Channel.CrmCardTransactionsByIntegrationMatchingData(param);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataResponse> CrmCardTransactionsByIntegrationMatchingDataAsync(Simant.TransportationService.CrmCardTransactionsByIntegrationMatchingDataRequest param)
        {
            return base.Channel.CrmCardTransactionsByIntegrationMatchingDataAsync(param);
        }
        
        public Simant.TransportationService.CrmCardTransactionsByCardIdsResponse CrmCardTransactionsByCardIds(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest)
        {
            return base.Channel.CrmCardTransactionsByCardIds(crmCardTransactionsByCardIdsRequest);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByCardIdsResponse> CrmCardTransactionsByCardIdsAsync(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest)
        {
            return base.Channel.CrmCardTransactionsByCardIdsAsync(crmCardTransactionsByCardIdsRequest);
        }
        
        public Simant.TransportationService.CrmCardTransactionsByCardIdsResponse CrmCardTransactionsByCardIdsARS(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest)
        {
            return base.Channel.CrmCardTransactionsByCardIdsARS(crmCardTransactionsByCardIdsRequest);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.CrmCardTransactionsByCardIdsResponse> CrmCardTransactionsByCardIdsARSAsync(Simant.TransportationService.CrmCardTransactionsByCardIdsRequest crmCardTransactionsByCardIdsRequest)
        {
            return base.Channel.CrmCardTransactionsByCardIdsARSAsync(crmCardTransactionsByCardIdsRequest);
        }
        
        public Simant.TransportationService.UpdateCustomerCardholderInformationResponse UpdateCustomerCardholderInformation(Simant.TransportationService.UpdateCustomerCardholderInformationRequest updateCustomerCardholderInformationRequest)
        {
            return base.Channel.UpdateCustomerCardholderInformation(updateCustomerCardholderInformationRequest);
        }
        
        public System.Threading.Tasks.Task<Simant.TransportationService.UpdateCustomerCardholderInformationResponse> UpdateCustomerCardholderInformationAsync(Simant.TransportationService.UpdateCustomerCardholderInformationRequest updateCustomerCardholderInformationRequest)
        {
            return base.Channel.UpdateCustomerCardholderInformationAsync(updateCustomerCardholderInformationRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransportationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransportationService))
            {
                return new System.ServiceModel.EndpointAddress("https://boseverestapp.birlesikodemesistemleri.com/IntegrationServiceTransportatio" +
                        "nService/SimAnt.Everest.BOS.Services.Integration.TransportationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransportationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITransportationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransportationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITransportationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITransportationService,
        }
    }
}
